### ISSUE TITLE
Shut down server 

### ISSUE THREAD

**Issue by aarvndhNG** [Terraria-Builders-Community/Banker#1]
[2023-02-17_11-59-00.log](https://github.com/Terraria-Builders-Community/Banker/files/10766473/2023-02-17_11-59-00.log)

**Comment by xtpkt** [comment]
Populate the connection string in auxillary.json, If you do not have that library or a mongoDB collection setup for your server instance, then you probably shouldn't be using this plugin...

**Comment by aarvndhNG** [comment]
How

**Comment by csmir** [comment]
We're not here to spoonfeed you

**Comment by xtpkt** [comment]
"How" -- This is your responsibility as a server operator to figure out, everything is open source and available to you. If you need help or explaining "How", then you probably shouldn't be hosting a tShock server..
